### ISSUE TITLE
data_2d_semantics images are all black

### ISSUE THREAD

**Issue by AreteQin** [robot-learning-freiburg/CoDEPS#1]
Hi there!

Thank you for your excellent work!

I ran your SemKITTI-DVPS example. And I got the following output:
```
Process train...
Copy depth: 100%|█████████████████████████████████████████████████████████████████████████████████| 19130/19130 [06:32<00:00, 48.69it/s]
Copy annotations: 100%|███████████████████████████████████████████████████████████████████████████| 38260/38260 [12:57<00:00, 49.20it/s]
Copy images: 0it [00:00, ?it/s]
Process val...
Copy depth: 100%|███████████████████████████████████████████████████████████████████████████████████| 4071/4071 [01:46<00:00, 38.31it/s]
Copy annotations: 100%|█████████████████████████████████████████████████████████████████████████████| 8142/8142 [03:05<00:00, 43.86it/s]
```
However, when I check the output semantic images, they are all black. I am not sure which image browser I should use. Or there is sth else I should pay attention to?

Sorry if I missed something already there. Thanks for any help in advance.

**Comment by vniclas** [comment]
Hi @AreteQin,

Thank you for the kind words.

The Semantic KITTI DVPS semantic images do not contain RGB information but each pixel indicates the ground truth class assignment. You can read it using Python as shown in our dataloader
https://github.com/robot-learning-freiburg/CoDEPS/blob/3bee37a6bb06bd2fb05377b2b8cf6379f419d7b1/datasets/sem_kitti_dvps.py#L129

For RGB visualization, you need to convert the class to an RGB value and save the result. You can find the common color convention in this file: https://github.com/robot-learning-freiburg/CoDEPS/blob/3bee37a6bb06bd2fb05377b2b8cf6379f419d7b1/datasets/cityscapes_labels.py#L84

Cheers
